### ISSUE TITLE
[BUG] Menu go to First Page

### ISSUE THREAD

**Issue by BlackYuzia** [Headline22/WeaponSpawner#2]
@Headline hi,
Great plug dude.

When I open Spawn menu and spawn any weapon in first page menu, all is good.
But when I spawn weapons in other (2-...) pages. Menu go to first page. That bad, not good.
You can fix that?

**Comment by BlackYuzia** [comment]
oh yea, and your plugin not save points to DB :c

**Comment by Headline** [comment]
I've just fixed the spawn menu opening at the start every time. 

About your other issues, check your error logs to see if database configuration is incorrect, or for more information about why queries may be failing. If you're sure that it's plugin error feel free to create another issue
