### ISSUE TITLE
[BUG] Not save Point Spawn

### ISSUE THREAD

**Issue by BlackYuzia** [Headline22/WeaponSpawner#3]
@Headline That me, again :d 

> L 03/04/2018 - 04:45:08: [hl_weaponspawner.smx] no such table: hl_weaponspawner

That error I get. I think that problem in plug. Not created table or some ...

**Comment by Headline** [comment]
The plugin will create the table if it does not exist, so perhaps there's another error?

**Comment by BlackYuzia** [comment]
Nope, only this.

**Comment by BlackYuzia** [comment]
@Headline you plug support **SQLite** type **db**? :c 
if not - I know why this shit not work :d

**Comment by BlackYuzia** [comment]
Okey, **MYSQL** fully worked :3

**Comment by BlackYuzia** [comment]
Solved
