### ISSUE TITLE
HL SPawner database

### ISSUE THREAD

**Issue by superblack4** [Headline22/WeaponSpawner#5]
So this is my hlspawner in database
Basically the first time I spawn the gun, it work. However, when i restart the server, the gun wasn't there anymore. Any solution?

"hl_weaponspawner"
	{
		"driver"			"sqlite"
		"host"				"localhost"
		"database"			"sourcemod"
		"user"				""
		"pass"				""	
		//"timeout"			"0"
		//"port"			"0"
	}

**Comment by Headline** [comment]
This plugin does not support SQLite, you’re going to need to use a mySQL server

**Comment by superblack4** [comment]
Can you give your example of database.cfg for mysql? :)
Also what type of databse am I need to use this plugin that go with MySql?

**Comment by Headline** [comment]
Did you happen to check the readme

**Comment by superblack4** [comment]
I did but I am not sure about the database part since when i use Sqilite, the plugin work but I don't know how to save the spawn point using mysql

**Comment by Headline** [comment]
If you don’t have a MySQL server you can’t use this plugin
